kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: incident-demo
nodes:
- role: control-plane
  extraPortMappings:
  # Prometheus
  - containerPort: 30090
    hostPort: 9090
    protocol: TCP
  # Sample app (checkout)
  - containerPort: 30080
    hostPort: 8888
    protocol: TCP
